/* CREATE ''fabricaMaderaDB' DATABASE */
CREATE SCHEMA fabricaMaderaDB;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER 'spq'@'%' IDENTIFIED BY 'spq';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON fabricaMaderaDB.* TO 'spq'@'%';