name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Build with Maven including only unit testing (with SonarCloud)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn --batch-mode --update-snapshots test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Prepare database for integration tests
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/dataBase.sql
          mvn --batch-mode --update-snapshots compile
      - name: Build with Maven including integration tests
        run: mvn --batch-mode --update-snapshots verify -Pintegracion
